### ISSUE TITLE
list_all_files not working

### ISSUE THREAD

**Issue by AbhilashPal** [kylemcdonald/SmileCNN#1]
`ImportError                               Traceback (most recent call last)
<ipython-input-19-ae1a83e43441> in <module>()
----> 1 import utils.list_all_files
      2 negative_paths = list(list_all_files('SMILEsmileD-master/SMILEs/negatives/negatives7/', ['.jpg']))
      3 print ('loaded', len(negative_paths), 'negative examples')
      4 positive_paths = list(list_all_files('SMILEsmileD-master/SMILEs/positives/positives7/', ['.jpg']))
      5 print ('loaded', len(positive_paths), 'positive examples')

D:\Machine Learning\MozofestHack\SmileCNN-master\utils\__init__.py in <module>()
----> 1 from list_all_files import list_all_files
      2 from show_array import show_array
      3 from make_mosaic import make_mosaic
      4 from crop_and_resize import crop_and_resize

ImportError: No module named 'list_all_files'`

**Comment by kylemcdonald** [comment]
This sounds like some kind of configuration error, i recommend copying and pasting the code from `utils/list_all_files.py` into the notebook.

**Comment by AbhilashPal** [comment]
Oh hell, my bad. I was only running the notebooks thinking utils is imported from Keras.
Thanks for the clarification.
